### ISSUE TITLE
[refactor-005] Доработать верстку регистрация/логин. Добавить валидацию. Настроить связь с беком.

### ISSUE THREAD

**Issue by AleksandrDronov** [Medical-Information/medical-information-frontend#112]
1. Доработать верстку. 
2. Установить пакеты formik и yup. Настроить валидацию всех полей.
3. Настроить связь с беком. Чтобы при авторизации пользователь логинился, а при регистрации регистрировался.

**Comment by elrouss** [comment]
Хорошо, постараюсь сделать к пятнице, чтобы успеть отдать на ревью Максиму
