### ISSUE TITLE
[data-008] Закрыть роут ЛК

### ISSUE THREAD

**Issue by AleksandrDronov** [Medical-Information/medical-information-frontend#161]
Необходимо сделать закрытый роут ЛК, на который может попасть только авторизированный пользователь.

**Comment by elrouss** [comment]
Ой, давай немного попозже? Нам в принципе нужно обсудить приватные роуты и что делать со всякими password-reset-confirmation и activation? Если что, у меня есть изящное решение по защите роутов

**Comment by elrouss** [comment]
Также закрываю регистрацию/авторизацию  для авторизованных и нужно решить, как быть с восстановлением email/подтверждением пароля (не забывать запретить навигацию назад по кнопке в браузере)
