### ISSUE TITLE
[shared-005] Чекбоксы

### ISSUE THREAD

**Issue by AleksandrDronov** [Medical-Information/medical-information-frontend#22]
1. Создать компонент checkbox в папке src/shared/checkbox. [https://ibb.co/bBKvCz9](https://ibb.co/bBKvCz9)
2. Создать историю в в папке src/shared/checkbox.

референс - [https://github.com/vierim/YaPomogayu-frontend/tree/develop/src/shared/ui/checkbox](https://github.com/vierim/YaPomogayu-frontend/tree/develop/src/shared/ui/checkbox)

**Comment by elrouss** [comment]
Могу взять)
