### ISSUE TITLE
[components-006] Хлебные крошки

### ISSUE THREAD

**Issue by AleksandrDronov** [Medical-Information/medical-information-frontend#34]
1. Создать компонент BreadСrumbs в папке src/components/bread-crumbs. [https://ibb.co/VSxX7yX](https://ibb.co/VSxX7yX) [https://ibb.co/brKtW1h](https://ibb.co/brKtW1h)
2. Создать историю в папке src/components/bread-crumbs.

Нетривиальная задача. Я делал, но как-то костыльно выглядело и в сторибук не осилил добавить.

**Comment by shuraaas** [comment]
хочу попробовать

**Comment by AleksandrDronov** [comment]
я так делал. [https://codesandbox.io/s/quirky-https-hg7zn2?file=/src/bredcrumbs-utils.ts](https://codesandbox.io/s/quirky-https-hg7zn2?file=/src/bredcrumbs-utils.ts)
