### ISSUE TITLE
[components-007] Карточка новостей для ленты новостей

### ISSUE THREAD

**Issue by AleksandrDronov** [Medical-Information/medical-information-frontend#35]
1. Создать компонент CardNews в папке src/components/card-news.  [https://ibb.co/KFCFLdT](https://ibb.co/KFCFLdT)
2. Создать историю в папке src/components/card-news.

**Comment by elrouss** [comment]
Поскольку я делал похожие компоненты и уже написал логику для даты и времени просмотра, могу взять в работу
