### ISSUE TITLE
[pages-001] Главная страница. Секция Задать вопрос врачу

### ISSUE THREAD

**Issue by AleksandrDronov** [Medical-Information/medical-information-frontend#41]
Выполнить верстку главной страницы. Секция Задать вопрос врачу

**Comment by elrouss** [comment]
Страницу можно собрать только тогда, когда будут готовые все остальные блоки. Прошу декомпозировать задачу и распределить между командой секции, а также ui, если не было сделано.

Я готов взять на себя секцию с "Задать вопрос врачу" и "Карточками с превью статей". Можешь также отдать мне redux toolkit и получение данных статей с сервера
